// GENERATED by jpp emit from module 'genlib' — do not edit.
const jpp = @import("jpp.zig");
const ints = @import("ints.zig");
const floats = @import("floats.zig");
const reals = @import("reals.zig");

const this_module = @This();
const STATIC = .{ this_module, ints, floats, reals };

pub const @"double" = jpp.MultiMethod("double", .{M0});

const M0 = jpp.Method(struct {
    pub const rank = 1;
    pub fn matches(comptime Args: []const type) bool {
        if (Args.len != 1) return false;
        return true;
    }
    pub fn Ret(comptime ctx: anytype, comptime Args: []const type) type {
        const ctx2 = jpp.extendAll(ctx, STATIC);
        const T0 = jpp.RetOfT(ctx2, "+", &.{ Args[0], Args[0] });
        return T0;
    }
    pub fn call(comptime ctx: anytype, args: anytype) Ret(ctx, jpp.argTypes(@TypeOf(args))) {
        const ctx2 = comptime jpp.extendAll(ctx, STATIC);
        const v0 = jpp.call(ctx2, "+", .{ args[0], args[0] });
        return v0;
    }
});
