// emit.zig — the printer: ast.Method + ast.FlatBody -> zig text.
// templates are the shapes hand-validated in spike/. each ANF op prints
// TWICE: at type level into Ret (return types may depend on context
// resolution) and at value level into call. mechanical by design.

const std = @import("std");
const ast = @import("ast.zig");

pub const MethodSpec = struct {
    method: ast.Method,
    flat: ast.FlatBody,
};

pub const ModuleSpec = struct {
    name: []const u8,
    usings: []const []const u8, // ORDERED — context priority
    methods: []const MethodSpec,
};

/// minimal growing text buffer (avoids std.io API churn)
pub const Out = struct {
    buf: []u8,
    len: usize = 0,

    pub fn add(self: *Out, comptime fmt: []const u8, args: anytype) void {
        const written = std.fmt.bufPrint(self.buf[self.len..], fmt, args) catch @panic("emit buffer full");
        self.len += written.len;
    }

    pub fn text(self: *const Out) []const u8 {
        return self.buf[0..self.len];
    }
};

pub fn emitModule(out: *Out, spec: ModuleSpec) void {
    out.add("// GENERATED by jpp emit from module '{s}' — do not edit.\n", .{spec.name});
    out.add("const jpp = @import(\"jpp.zig\");\n", .{});
    for (spec.usings) |u|
        out.add("const {s} = @import(\"{s}.zig\");\n", .{ u, u });
    out.add("\nconst this_module = @This();\n", .{});
    out.add("const STATIC = .{{ this_module", .{});
    for (spec.usings) |u| out.add(", {s}", .{u});
    out.add(" }};\n", .{});

    // multimethod decls: surface names verbatim via @"..."
    // v1: one method per name; grouping same-named methods comes with the reader
    for (spec.methods, 0..) |m, i|
        out.add("\npub const @\"{s}\" = jpp.MultiMethod(\"{s}\", .{{M{d}}});\n", .{ m.method.name, m.method.name, i });

    for (spec.methods, 0..) |m, i|
        emitMethod(out, m, i);
}

fn emitMethod(out: *Out, spec: MethodSpec, idx: usize) void {
    const m = spec.method;
    const slots = m.value_params orelse &.{};

    out.add("\nconst M{d} = jpp.Method(struct {{\n", .{idx});

    // rank: sum of slot ranks (exact=3, predicate=2, bare=1, variadic=0)
    var rank: u32 = 0;
    for (slots) |s| rank += if (s.variadic) 0 else switch (s.qual) {
        .exact => @as(u32, 3),
        .predicate => 2,
        .bare => 1,
    };
    out.add("    pub const rank = {d};\n", .{rank});

    // matches: arity + per-slot conjuncts (the pack pattern)
    out.add("    pub fn matches(comptime Args: []const type) bool {{\n", .{});
    out.add("        if (Args.len != {d}) return false;\n", .{slots.len});
    for (slots, 0..) |s, i| switch (s.qual) {
        .exact => |e| out.add("        if (Args[{d}] != {s}) return false;\n", .{ i, e.kind.symbol }),
        .predicate => |p| out.add("        if (!{s}(Args[{d}])) return false;\n", .{ p.kind.symbol, i }),
        .bare => {},
    };
    out.add("        return true;\n    }}\n", .{});

    // Ret: type-level mirror of the body's op vector
    out.add("    pub fn Ret(comptime ctx: anytype, comptime Args: []const type) type {{\n", .{});
    out.add("        const ctx2 = jpp.extendAll(ctx, STATIC);\n", .{});
    if (spec.flat.ops.len == 0) out.add("        _ = ctx2;\n", .{});
    for (spec.flat.ops) |op| emitOpType(out, op);
    out.add("        return ", .{});
    emitRefType(out, spec.flat.result);
    out.add(";\n    }}\n", .{});

    // call: value-level body
    out.add("    pub fn call(comptime ctx: anytype, args: anytype) Ret(ctx, jpp.argTypes(@TypeOf(args))) {{\n", .{});
    out.add("        const ctx2 = comptime jpp.extendAll(ctx, STATIC);\n", .{});
    if (spec.flat.ops.len == 0) out.add("        _ = ctx2;\n", .{});
    for (spec.flat.ops) |op| emitOpValue(out, op);
    out.add("        return ", .{});
    emitRefValue(out, spec.flat.result);
    out.add(";\n    }}\n}});\n", .{});
}

fn emitOpType(out: *Out, op: ast.Op) void {
    switch (op.kind) {
        .call => |c| {
            out.add("        const T{d} = jpp.RetOfT(ctx2, \"{s}\", &.{{ ", .{ op.id, c.callee });
            for (c.paren_args, 0..) |r, i| {
                if (i > 0) out.add(", ", .{});
                emitRefType(out, r);
            }
            out.add(" }});\n", .{});
        },
        else => @panic("emit v1: only call ops"),
    }
}

fn emitOpValue(out: *Out, op: ast.Op) void {
    switch (op.kind) {
        .call => |c| {
            out.add("        const v{d} = jpp.call(ctx2, \"{s}\", .{{ ", .{ op.id, c.callee });
            for (c.paren_args, 0..) |r, i| {
                if (i > 0) out.add(", ", .{});
                emitRefValue(out, r);
            }
            out.add(" }});\n", .{});
        },
        else => @panic("emit v1: only call ops"),
    }
}

fn emitRefType(out: *Out, r: ast.ValRef) void {
    switch (r) {
        .param => |i| out.add("Args[{d}]", .{i}),
        .local => |i| out.add("T{d}", .{i}),
        else => @panic("emit v1: param/local refs only"),
    }
}

fn emitRefValue(out: *Out, r: ast.ValRef) void {
    switch (r) {
        .param => |i| out.add("args[{d}]", .{i}),
        .local => |i| out.add("v{d}", .{i}),
        else => @panic("emit v1: param/local refs only"),
    }
}

// --- demo driver: emit `double` from the living example in ast.zig ----------

pub fn main() !void {
    var buf: [64 * 1024]u8 = undefined;
    var out = Out{ .buf = &buf };

    emitModule(&out, .{
        .name = "genlib",
        .usings = &.{ "ints", "floats", "reals" },
        .methods = &.{
            .{ .method = ast.example_double, .flat = ast.example_double_flat },
        },
    });

    var threaded = std.Io.Threaded.init(std.heap.page_allocator, .{});
    const io = threaded.io();
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = "spike/gen_double.zig", .data = out.text() });
    std.debug.print("wrote spike/gen_double.zig ({d} bytes)\n", .{out.len});
}
